import { DietKey } from '../types';

export const TRIGGER_LISTS: Record<DietKey, string[]> = {
  glutenFree: [
    'wheat', 'wheat flour', 'wheat starch', 'wheat bran', 'wheat germ',
    'modified wheat starch', 'wheat protein', 'hydrolysed wheat',
    'barley', 'barley malt', 'barley flour',
    'rye', 'rye flour',
    'triticale',
    'malt', 'malt extract', 'malt flavour', 'malt vinegar',
    'brewers yeast', "brewer's yeast",
    'semolina', 'spelt', 'farro', 'kamut',
    'einkorn', 'emmer', 'durum', 'bulgur', 'couscous',
    'seitan', 'gluten', 'oats', 'oat flour',
  ],

  dairyFree: [
    'milk', 'milk solids', 'milk powder', 'skim milk', 'whole milk',
    'milk fat', 'milk protein', 'condensed milk', 'evaporated milk',
    'lactose', 'lactalbumin', 'lactoglobulin',
    'casein', 'caseinate', 'sodium caseinate', 'calcium caseinate',
    'whey', 'whey powder', 'whey protein', 'sweet whey',
    'butter', 'butter oil', 'buttermilk', 'butter fat',
    'cream', 'sour cream', 'cream cheese',
    'cheese', 'cheddar', 'parmesan', 'mozzarella',
    'yoghurt', 'yogurt',
    'ghee', 'custard', 'ice cream',
    'lactulose', 'recaldent',
  ],

  lowFodmap: [
    'garlic', 'garlic powder', 'garlic extract',
    'onion', 'onion powder', 'onion extract', 'spring onion',
    'leek', 'shallot',
    'inulin', 'chicory root', 'chicory extract',
    'fructooligosaccharides', 'fos',
    'high fructose corn syrup', 'fructose',
    'honey',
    'apple', 'pear', 'mango', 'watermelon',
    'sorbitol', 'mannitol', 'xylitol', 'maltitol', 'isomalt',
    'wheat', 'rye', 'barley',
    'lactose',
    'legume', 'lentil', 'chickpea', 'kidney bean',
    'cashew', 'pistachio',
  ],

  lowGI: [
    'glucose', 'glucose syrup', 'dextrose',
    'maltodextrin', 'maltose',
    'white flour', 'refined flour',
    'corn syrup', 'high fructose corn syrup',
    'sugar', 'cane sugar', 'white sugar',
    'modified starch', 'tapioca starch',
    'white rice', 'rice flour',
    'potato starch', 'potato flour',
    'bread crumbs',
  ],

  lowHistamine: [
    'vinegar', 'wine vinegar', 'cider vinegar', 'balsamic vinegar',
    'fermented', 'fermented soy', 'soy sauce', 'tamari',
    'yeast', 'yeast extract', 'autolysed yeast',
    'aged cheese', 'parmesan', 'blue cheese', 'camembert',
    'processed meat', 'salami', 'pepperoni', 'bacon', 'ham',
    'smoked fish', 'smoked salmon', 'anchovies',
    'tomato', 'tomato paste', 'tomato sauce',
    'spinach', 'eggplant', 'avocado',
    'strawberry', 'raspberry', 'citrus',
    'alcohol', 'wine', 'beer',
    'chocolate', 'cocoa',
    'msg', 'monosodium glutamate',
    'artificial colours', 'artificial flavours',
  ],
};